require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.4'

target 'OnviTV' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => File.expand_path('..', __dir__),
  )

  target 'OnviTVTests' do
    inherit! :complete
  end

  post_install do |installer|
    # Fix deployment targets for all pods to 13.0 minimum
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
      end
    end
    
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
